spring.application.name=SpringSecurity
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/myDatabase
spring.datasource.username=postgres
spring.datasource.password=postgres

jpa.hibernate.ddl-auto=update
jpa.hibernate.show-sql=true
jpa.hibernate.database=postgresql
jpa.hibernate.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.username=admin
spring.security.user.password=admin
spring.security.user.roles=ADMIN
